grid:
  rows: 2
  cols: 2
pages:
- name: Dashboard
  url: http://localhost:5001
  zoom: 0.65
  position:
  - 0
  - 0
- name: Disk Watcher
  url: http://localhost:5002
  zoom: 0.9
  position:
  - 0
  - 1
- name: Heart Beats
  url: http://localhost:5003
  zoom: 1.0
  position:
  - 1
  - 0
- name: FTS
  url: http://localhost:8080
  zoom: 1.0
  position:
  - 1
  - 1
splitter_sizes:
  vertical:
  - 582
  - 431
  horizontal:
  - - 378
    - 887
  - - 267
    - 998
