grid:
  rows: 2
  cols: 2
pages:
- name: Dashboard
  url: http://localhost:5001
  position:
  - 0
  - 0
- name: Disk Watcher
  url: http://localhost:5002
  position:
  - 0
  - 1
- name: Heart Beats
  url: http://localhost:5003
  position:
  - 1
  - 0
- name: FTS
  url: http://localhost:8080
  position:
  - 1
  - 1
splitter_sizes:
  vertical:
  - 375
  - 375
  horizontal:
  - - 868
    - 397
  - - 379
    - 886
